### ISSUE TITLE
grails prepare-test failing

### ISSUE THREAD

**Issue by uppaljs** [WebDataConsulting/billing#13]
Hi,

I am trying to setup jbilling from source , but I am running into some errors:

| Environment set to development.....
Loading configuration files from classpath
Loading database version 4.1
jdbc:postgresql://localhost:5432/jbilling_test jbilling/[no password](schema: public) (driver org.postgresql.Driver)
dropping all objects in jbilling_test
Cleaning the ActiveMQ data directory...
updating with context = test. Loading test data
Loading upgrade descriptors/database/jbilling-upgrade-3.2.xml
Loading upgrade descriptors/database/jbilling-upgrade-3.3.xml
Loading upgrade descriptors/database/jbilling-upgrade-3.4.xml
Loading upgrade descriptors/database/jbilling-upgrade-4.0.xml
Loading upgrade descriptors/database/jbilling-upgrade-4.1.xml
| Error Error executing script PrepareTest: : liquibase.exception.MigrationFailedException: Migration failed for change set descriptors/database/jbilling-upgrade-4.1.xml::2 Added missing jbilling-mediation-2.x-1::Manisha Gupta:
     Reason: liquibase.exception.DatabaseException: Error executing SQL INSERT INTO public.mediation_cfg (id, entity_id, create_datetime, name, order_value, pluggable_task_id, optlock) VALUES (20.0, 1.0, '2009-01-13 11:16:50.976', 'JDBCReader test', 2.0, 480.0, 0.0): ERROR: insert or update on table "mediation_cfg" violates foreign key constraint "mediation_cfg_fk_1"
  Detail: Key (pluggable_task_id)=(480) is not present in table "pluggable_task". (Use --stacktrace to see the full trace)

Any pointers / fix?

**Comment by vikasbo** [comment]
@uppaljs There is a problem with this changeSet.

jbilling-upgrade-4.1.xml::2 Added missing jbilling-mediation-2.x-1

We can fix this by Monday. Thanks for pointing out @uppaljs.

Regards
Vikas

**Comment by vikasbo** [comment]
@uppaljs This issue is fixed. Thank you very much for reporting. 

I would like to add that you should have shared the command you used to arrive at this error. Helps in reproducing an issue faster. I can guess that you used `grails prepare-test`. This command in its current form is only required by some tool like Jenkins to trigger automated test.

In your case, in order to setup #jBilling, you should have used a different version `grails prepare-test -init`.

Best Regards,
Vikas
